### ISSUE TITLE
使用new Invoker 直接连接Dubbo 需要指定path参数否则报错

### ISSUE THREAD

**Issue by babybreath** [Corey600/zoodubbo#8]
const invoker = new ZD.Invoker(
  'dubbo://[host]/[port]/[path]?interface=[path]&methods=[methods]',
  **{path: [path]}**
)
必须在参数中指定path字段否则报错

**Comment by yueyangxiaoyi** [comment]
{ NO_NODE: Exception: NO_NODE[-101]
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
  code: -101,
  name: 'NO_NODE',
  path: undefined,
  message: 'Exception: NO_NODE[-101]' }

这个是什么问题呢？我向刚才上面那样设置也不能成功

**Comment by Corey600** [comment]
@yueyangxiaoyi 看看这个错误是哪个模块报出的，我猜可能是 zookeeper 节点没找到
